language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-clover=clover.xml
  - vendor/bin/spiral-cs check src tests functions.php

after_script:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml